eureka:
  client:
    service-url:
      defaultZone: http://${diy.eureka.user:smile}:${diy.eureka.password:smilelxy}@${diy.eureka.host.master:eureka-master}:${diy.eureka.server.port:8761}/eureka,http://${diy.eureka.user:smile}:${diy.eureka.password:smilelxy}@${diy.eureka.host.backup01:eureka-backup01}:${diy.eureka.server.port:8761}/eureka